create table RECIPES(
   ID INT NOT NULL AUTO_INCREMENT,
   NAME VARCHAR(200) NOT NULL,
   DESCRIPTION VARCHAR(500) NOT NULL,
   INSTRUCTIONS VARCHAR(1000) NOT NULL,
   IMAGE_PATH VARCHAR(500) NOT NULL,
   PRIMARY KEY ( ID )
);

